/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.codefish.syncafy;

public final class R {
    public static final class anim {
        public static final int fadein=0x7f040000;
    }
    public static final class array {
        public static final int about_artists=0x7f070004;
        public static final int about_authors=0x7f070001;
        /**  Add your name here if you helped out 
 <item></item> 
         */
        public static final int about_documenters=0x7f070002;
        /**  Add your name here if you helped out, but only in the arrays.xml for the localization that you helped to translate into! 
 <item></item>  
         */
        public static final int about_translators=0x7f070003;
        public static final int feedbacktypelist=0x7f070000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int arrow=0x7f020000;
        public static final int feedback=0x7f020001;
        public static final int ic_launcher_folder=0x7f020002;
        public static final int ic_launcher_folder_open=0x7f020003;
        public static final int ic_launcher_home=0x7f020004;
        public static final int ic_launcher_home_small=0x7f020005;
        public static final int ic_menu_back_small=0x7f020006;
        public static final int ic_menu_forward_small=0x7f020007;
        public static final int icon_file=0x7f020008;
        public static final int icon_sdcard=0x7f020009;
        public static final int icon_sdcard_small=0x7f02000a;
        public static final int main_background=0x7f02000b;
        public static final int settings=0x7f02000c;
        public static final int wheel_bg=0x7f02000d;
        public static final int wheel_val=0x7f02000e;
        public static final int white_border=0x7f02000f;
    }
    public static final class id {
        public static final int ButtonSendFeedback=0x7f090009;
        public static final int EditTextFeedbackBody=0x7f090008;
        public static final int EditTextName=0x7f090005;
        public static final int EditTextTwitter=0x7f090006;
        public static final int LinearLayout01=0x7f09001a;
        public static final int ScrollView01=0x7f090003;
        public static final int SpinnerFeedbackType=0x7f090007;
        public static final int TextViewTitle=0x7f090004;
        public static final int add_panel=0x7f090000;
        public static final int button_directory_pick=0x7f090011;
        public static final int button_pick=0x7f090013;
        public static final int directory_buttons=0x7f09000e;
        public static final int directory_input=0x7f09000f;
        public static final int directory_text=0x7f090010;
        public static final int dirfile_view=0x7f09001b;
        public static final int empty=0x7f090014;
        public static final int empty_text=0x7f090015;
        public static final int feedbackButton=0x7f09002c;
        public static final int filename=0x7f090012;
        public static final int foldername=0x7f090002;
        public static final int foldernametext=0x7f090001;
        public static final int ftp_password=0x7f090029;
        public static final int ftp_user=0x7f090028;
        public static final int icon=0x7f090017;
        public static final int info=0x7f090019;
        public static final int isRecursive=0x7f09000d;
        public static final int number_wheel=0x7f09002a;
        public static final int pickDirectory=0x7f09000b;
        public static final int radio_dropbox=0x7f090027;
        public static final int radio_ftp=0x7f090025;
        public static final int radio_sftp=0x7f090026;
        public static final int scan_progress=0x7f090016;
        public static final int schedule=0x7f09001e;
        public static final int schedule_sync=0x7f09001c;
        public static final int selectedDirectory=0x7f09000c;
        public static final int server_address=0x7f090022;
        public static final int server_directory=0x7f090023;
        public static final int server_label=0x7f090020;
        public static final int server_layout=0x7f09000a;
        public static final int server_port=0x7f090021;
        public static final int server_type=0x7f090024;
        public static final int server_view=0x7f09001f;
        public static final int sync=0x7f09001d;
        public static final int text=0x7f090018;
        public static final int unit_wheel=0x7f09002b;
    }
    public static final class layout {
        public static final int add_button=0x7f030000;
        public static final int dialog_new_folder=0x7f030001;
        public static final int feedback_form=0x7f030002;
        public static final int file_form=0x7f030003;
        public static final int filelist=0x7f030004;
        public static final int filelist_item=0x7f030005;
        public static final int main=0x7f030006;
        public static final int server_form=0x7f030007;
        public static final int wheel_layout=0x7f030008;
    }
    public static final class menu {
        public static final int menu=0x7f080000;
    }
    public static final class string {
        public static final int about_comments=0x7f060007;
        /**  ***************************
	     About information
	     *************************** 
         */
        public static final int about_copyright=0x7f060036;
        public static final int about_email=0x7f060038;
        /**  END Feedback 
 ***************************
	     About information
	     *************************** 
 Automatically filled in by Launchpad: 
         */
        public static final int about_translators=0x7f060006;
        public static final int about_website_label=0x7f060008;
        public static final int about_website_url=0x7f060037;
        /**  ***************************
	     Applicatio-specific strings
	     *************************** 
         */
        public static final int app_name=0x7f06000a;
        public static final int application_not_available=0x7f060035;
        /**  Construct a unique file name of a file called %s. 
         */
        public static final int copied_file_name=0x7f060024;
        /**  Construct a unique file name with number %1$d of a file called %2$s. 
         */
        public static final int copied_file_name_2=0x7f060025;
        public static final int copy_button=0x7f060023;
        public static final int copy_title=0x7f060022;
        public static final int create_new_folder=0x7f060014;
        /**  Feedback 
         */
        public static final int email_address=0x7f060001;
        public static final int error_copying_file=0x7f06002f;
        public static final int error_creating_new_folder=0x7f060028;
        public static final int error_deleting_child_file=0x7f060031;
        public static final int error_deleting_file=0x7f060029;
        public static final int error_deleting_folder=0x7f06002a;
        public static final int error_file_does_not_exists=0x7f060030;
        public static final int error_generic=0x7f060032;
        public static final int error_media_scan=0x7f060033;
        public static final int error_moving_file=0x7f06002d;
        public static final int error_moving_folder=0x7f06002e;
        public static final int error_renaming_file=0x7f06002b;
        public static final int error_renaming_folder=0x7f06002c;
        /**  ***************************
	     Distribution
	     *************************** 
 EULA 
         */
        public static final int eula_title=0x7f060009;
        public static final int feedbacktype1=0x7f060002;
        public static final int feedbacktype2=0x7f060003;
        public static final int feedbacktype3=0x7f060004;
        public static final int feedbacktype4=0x7f060005;
        public static final int file_copied=0x7f06001f;
        public static final int file_deleted=0x7f060019;
        public static final int file_moved=0x7f06001d;
        public static final int file_name=0x7f060016;
        public static final int file_renamed=0x7f06001b;
        public static final int folder_deleted=0x7f06001a;
        public static final int folder_moved=0x7f06001e;
        public static final int folder_name=0x7f060015;
        public static final int folder_renamed=0x7f06001c;
        public static final int media_scan_excluded=0x7f060027;
        public static final int media_scan_included=0x7f060026;
        public static final int menu_copy=0x7f060011;
        public static final int menu_delete=0x7f06000c;
        public static final int menu_exclude_from_media_scan=0x7f060013;
        public static final int menu_include_in_media_scan=0x7f060012;
        public static final int menu_move=0x7f060010;
        public static final int menu_new_folder=0x7f06000b;
        public static final int menu_open=0x7f06000f;
        public static final int menu_rename=0x7f06000d;
        public static final int menu_send=0x7f06000e;
        public static final int move_button=0x7f060021;
        public static final int move_title=0x7f060020;
        public static final int really_delete=0x7f060018;
        public static final int send_not_available=0x7f060034;
        public static final int this_folder_is_empty=0x7f060017;
        public static final int update_app_developer_url=0x7f06003a;
        /**  ***************************
	     Distribution
	     *************************** 
 Update 
         */
        public static final int update_app_url=0x7f060039;
        /**  ********************************
                    SYNCAFY
         ******************************** 
         */
        public static final int welcome_message=0x7f060000;
    }
    public static final class xml {
        public static final int mimetypes=0x7f050000;
    }
}
